---
# tasks file for nodejs
- name: Download nodejs
  shell: 'wget http://nodejs.org/dist/v{{node_major}}.{{node_minor}}.{{node_patch}}/node-v{{node_major}}.{{node_minor}}.{{node_patch}}-linux-x64.tar.gz chdir=/opt creates=node-v{{node_major}}.{{node_minor}}.{{node_patch}}-linux-x64.tar.gz'
- name: Unarchive nodejs
  shell: tar --strip-components 1 -xzvf /opt/node-v{{node_major}}.{{node_minor}}.{{node_patch}}-linux-x64.tar.gz -C /usr/local creates=/usr/local/bin/node
